import "./globals.css";
import { Exo_2 } from "next/font/google";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Provider from "@/SessionProvider";

const exo2 = Exo_2({ subsets: ["latin"] });

export const metadata = {
  title: "Singh's Blog Set's",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
    <html lang="en">
      <body className={`bg-rose-50 ${exo2.className}`}>
        <Provider>
          <Navbar />
          {children}
          <Footer />
        </Provider>
      </body>
    </html>
  );
}
